### ISSUE TITLE
Did not show any results until source changed.

### ISSUE THREAD

**Issue by malipetek** [Kamahl19/hain-plugin-best-torrent#1]
"www.torrentz.eu" is redirecting to ad pages like 5-6 times. I have replaced composerUrl.url property with "www.newtorrentz.com" and it works like a charm.

**Comment by Kamahl19** [comment]
Could you please send a pull request?

**Comment by Kamahl19** [comment]
@malipetek Hi, I have already pushed the fix. Thanks for the issue.
